name: MooTools-DatePicker
author: astolwijk
current: 1.50b4
category: Widgets
tags: [Datepicker,Calendar]
demo: http://www.aryweb.nl/projects/mootools-datepicker/
docs: http://github.com/arian/mootools-datepicker/blob/master/README.md
copyright: "&copy; [MonkeyPhysics.com](http://monkeyphysics.com)"
license: MIT
web: "[aryweb.nl/projects/mootools-datepicker](http://www.aryweb.nl/projects/mootools-datepicker/)"
description: MooTools Datepicker class
sources:
  - "Source/datepicker.js"